name: integrate

on:
  push:
    branches:
      - integrate

jobs:
  lint:
    uses: spuxx1701/ci/.github/workflows/npm_lint.yml@v1.0

  docker_build_and_push:
    needs: lint
    uses: spuxx1701/ci/.github/workflows/docker_build_and_push.yml@v1.0
    with:
      username: spuxx
      repository: doleo-2-backend
      environment: integrate
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}

  finish:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - id: log
        run: echo ${{ needs.docker_push.outputs.tags }}
